      INSERT INTO COMMUNITY (NAME) VALUES ('COMMUNITY-A');
      INSERT INTO COMMUNITY (NAME) VALUES ('COMMUNITY-B');
      INSERT INTO COMMUNITY (NAME) VALUES ('COMMUNITY-C');
      INSERT INTO COMMUNITY (NAME) VALUES ('COMMUNITY-D');
